README.md

In the future we could have something like
```
We already of creating recordings from different environments:
- [A Kong plugin](..)
– [A plugin to Spring Cloud Gateway](...)
- [An npm library to intercept HTTP requests](...)
- [...]
If your configuration is not listed here, you can generate these files yourself using code in your application or a script to process log files using the below documented format.
```

Document JSON Lines input format

---

LICENSE
README.md
setup.py

Add `LICENSE`, installation instructions, and more badges.

Prepare for release.

---

README.md
meeshkan/__init__.py
meeshkan/schemabuilder/__init__.py
meeshkan/schemabuilder/builder.py

Add more stuff to README, define top-level imports.
TODO:

Tweak readme, define top-level imports.

---

meeshkan/schemabuilder/builder.py
meeshkan/schemabuilder/query.py
meeshkan/schemabuilder/servers.py
setup.py

Upgrade to openapi-typed 0.1.0 added lots of type-check errors so fix those.

Upgrade to openapi-typed 0.1.0.

---

meeshkan/gen/generator.py
setup.py
tests/generator/faker_test.py
tests/generator/generator_test.py
tests/generator/matcher_test.py

A python port of the unmock generator

Ports generator from unmock

---

.gitignore
setup.py

Fixes https://github.com/Meeshkan/meeshkan/network/alert/setup.py/urllib3/open
Also adds .idea/ to .gitignore for PyCharm users.

Bump version of urllib3 dependency

---

README.md

There is a lot more to do to improve the README, but let's start with the initial description!

Update start of README

---

MANIFEST.in
meeshkan/gen/generator.py
meeshkan/schemabuilder/builder.py
meeshkan/schemabuilder/operation.py
meeshkan/schemabuilder/paths.py
meeshkan/schemabuilder/schemadiff.py
setup.py
tests/generator/matcher_test.py
tests/schemabuilder/builder_test.py

These are optimizations for the schema builder.  There are currently tests that are broken, so it needs fixing.  Once done, there will be a 100-1000x time optimization for schema building.

Code to speed stuff up

---

meeshkan/schemabuilder/writer.py
meeshkan/server/server/response_matcher.py
tests/main_test.py

This gets a ~100x speed improvement over yaml.
Downside is that it inflates the file size 2x, but the speedup for real-world APIs is worth it IMO.

Makes JSON primary output and input format.

---

meeshkan/server/commands.py

Currently:
```sh
$ meeshkan
Usage: meeshkan [OPTIONS] COMMAND [ARGS]...
Meeshkan CLI.
Options:
--help  Show this message and exit.
Commands:
build    Build OpenAPI schema from HTTP exchanges.
convert  Convert recordings from PCAP to JSONL format.
mock
record   Record http traffic to http-types format.
```
After this PR:
```sh
Usage: meeshkan [OPTIONS] COMMAND [ARGS]...
Meeshkan CLI.
Options:
--help  Show this message and exit.
Commands:
build    Build OpenAPI schema from HTTP exchanges.
convert  Convert recordings from PCAP to JSONL format.
mock     Run a mock server.
record   Record http traffic to http-types format.
```

Add a description for the mock command

---

README.md

We're lacking a direct channel for feedback - let's start with something like this?
Personally "to let us know about questions, problems or ideas" feels a bit uninspiring, so alternative wording is really welcome!

Add link to chat room on Gitter

---

.circleci/config.yml
pytest.ini

Call integreation tests on master commits

---

meeshkan/serve/utils/data_callback.py
pytest.ini
tests/serve/utils/test_data_callback.py

Closes #117 
It was broken after migration to dataclasses

correct schema creation in proxy

---

meeshkan/serve/commands.py
meeshkan/serve/record/proxy.py

It's not used for anything at the moment, we can add it back later if needed.

Do not start admin server in record.

---

tests/serve/mock/schemas/nordea/ais-v4.json
tests/serve/mock/test_nordea.py

Include a bunch of (skipped) failing tests that we will need to support the Nordea sandbox. I would like to first include these in the repo and and then proceed fixing them one-by-one.
~Fails with `could not find a method get for path /personal/v4/accounts on hostname api.nordeaopenbanking.com.` even though it should be there: https://github.com/meeshkan/meeshkan/blob/nordea-bug/tests/serve/mock/schemas/nordea/ais-v4.json~ Problem was the missing auth.

Tests for Nordea OpenBanking API

---

meeshkan/serve/commands.py

A fix after https://github.com/meeshkan/meeshkan/pull/148.

Remove admin_port argument to record

---

meeshkan/serve/mock/server.py
meeshkan/serve/record/proxy.py

log meeshkan is running

---

meeshkan/build/nlp/entity_normalizer.py
meeshkan/build/nlp/main.py
meeshkan/build/nlp/schema_normalizer/schema_paths/schema_reference.py

@aby2s  and @MariaMalitckaya . Merging the changes done so far.

adding test cases

---

meeshkan/__main__.py
meeshkan/build/paths.py
meeshkan/serve/admin/runner.py
meeshkan/serve/commands.py
meeshkan/serve/mock/server.py
meeshkan/serve/record/proxy.py
meeshkan/tutorial/__init__.py
setup.py
tests/tutorial/test_tutorial.py

The issue is that this significantly increases the amount of time the tests take. It's possible to add conditional skip flags, etc but not sure the best way to do it.

Adds tutorial to Meeshkan

---

.github/ISSUE_TEMPLATE/bug-report----.md
.github/ISSUE_TEMPLATE/feature-request----.md
.github/ISSUE_TEMPLATE/question---.md
.github/PULL_REQUEST_TEMPLATE.md

Closes #193.
Added a PR template as well as three different issue templates 🙌 
Based on what we had for https://github.com/meeshkan/unmock-js so open to any other suggestions and comments. 
Covers MEM-270/MEM-269 on Linear.

Add PR and issue templates

---

README.md

Fixes #<issue number>
No issue number
Fixed the link to the Gitter community
Check the destination.  Click the link.

Updating Gitter link

---

docs/BUILD.md
docs/MOCK.md
docs/RECORD.md

Fixes #208 
* Updated links to external sites (https://example.com)
* Updated relative links (../markdown)
* Added missing Table of Contents (It was out of sync)
* Pull the branch
* Click the links or use your favorite MD link checker
* Celebrate

#208 ran docs/ through a MD link checker

---

setup.py

Fixes #216
Update urllib3 to 1.25.10

Update urllib3 to 1.25.10
