.circleci/config.yml, meeshkan/schemabuilder/builder.py
Without this type annotation pyright >= 1.1.14 fails with a:
RangeError: Maximum call stack size exceeded
Fixes #1.
=> Add type annotation to not crash newer pyright

README.md, setup.py
Enables accessing CLI as `meeshkan` instead of `python -m meeshkan`.
=> Add entrypoint to CLI.

.gitignore, meeshkan/__main__.py, meeshkan/schemabuilder/result.py, meeshkan/schemabuilder/writer.py, tests/main_test.py
Closes #9.
- Takes a directory as output destination. Defaults to `out/`.
- Currently only writes `openapi.yaml` in the destination.
- Added some reading and writing code and a very simple data type for the build result.
=> Write builder output to folder.

README.md
We lost this in the transition from unmock-sniffer:
Without the quotes around `[]`, zsh (which is the default shell on macOS nowadays), fails with `zsh: no matches found: .[dev]`.
=> Be zsh compatible in the README instruction

meeshkan/schemabuilder/__init__.py, meeshkan/schemabuilder/builder.py, meeshkan/schemabuilder/paths.py, tests/schemabuilder/builder_test.py, tests/schemabuilder/paths_test.py, tests/util.py
- Add `meeshkan.schemabuilder.paths` module for working with paths. For example, add code for matching path such as `/pets/{petId}` to `/pets/32`
- Add checks in `builder.py` for checking the path parameters are valid. This is mostly a sanity check for now, as the builder does not yet try to infer parameters from paths. This means that if request contains paths such as `/pets/1` and `/pets/2`, the builder doesn't yet try to combine them to `/pets/{id}`
Next steps:
=> Add code for manipulating path parameters.

meeshkan/schemabuilder/builder.py, meeshkan/schemabuilder/query.py, tests/schemabuilder/builder_test.py, tests/schemabuilder/paths_test.py, tests/schemabuilder/query_test.py
Closes #21.
- Read query parameters from request and use them to store the query parameters at the `Operation` level
- Sets the type of query parameters only on the first go for now, does not update the type (wouldn't be hard to add that)
=> Infer query parameters from requests.

meeshkan/schemabuilder/builder.py, meeshkan/schemabuilder/servers.py, setup.py, tests/schemabuilder/builder_test.py, tests/schemabuilder/servers_test.py
Closes #22.
- Normalize request path (e.g. /v1/pets) by the basepath in server URL (/v1). The result for the example is `/pets`.
- Does not construct a server URL for unknown server (#13)
=> Respect base path from schema servers field.

meeshkan/schemabuilder/builder.py
The build of https://github.com/Meeshkan/meeshkan/pull/27 didn't detect that, as it doesn't test against the result of the merge, and the code in question was added after PR 27 was created.
=> Adopt to 'req' -> 'request' renaming in py-http-types

meeshkan/schemabuilder/builder.py, meeshkan/schemabuilder/media_types.py, tests/schemabuilder/builder_test.py
- Fix bug where a non-json text body such as "Hello" raised an exception instead of setting the schema as `{type: "string" }`
- Add new `media_types.py` module for all code related to building media types from bodies
=> Fix bug: non-json body raises an exception.

tests/schemabuilder/builder_test.py
I think using hamcrest matchers here would make the intent of the test a bit clearer.
=> Simplify test with hamcrest matchers.

meeshkan/gen/generator.py, tests/generator/matcher_test.py
This is necessary when the protocol is not available.
=> Allow server in openapi spec without protocol to pass if host matches

meeshkan/__main__.py, meeshkan/schemabuilder/builder.py, meeshkan/sources/kafka.py, tests/sources/test_kafka.py
- Necessary changes to get [this demo](https://github.com/Meeshkan/meeshkan-express-kafka-demo) running
- Get rid of `KafkaProcessor`, replace with single `KafkaSource`
- Fix the stream conversion: `agent.stream()` returns a stream of dictionaries instead of the "result" stream (stream of HttpExchange objects) so one needs another transform to transform the dictionaries to HttpExchange objects
=> Fix Kafka source.

README.md
Since we no longer have a hello world, I thought it'd be nice to add more instructions for how people can use the tutorial rather than making them open a separate repo 🤷‍♀ 
I also added some minor text fixes including:
- Updating the ToC
- Formatting the version notes
- Adding the clone step to getting started part of the development guide
=> Add tutorial instructions

guides/MOCK.md, guides/RECORD.md, meeshkan/server/commands.py
- Minor wording changes.
- The `-H '{"Host": "my.api.com", "X-Meeshkan-Scheme": "https"}'` construction does not work for me with curl, replace with `-H "Host: "my.api.com" -H "X-Meeshkan-Scheme: https"` which does.
- Fix typo `X-Meeshkan-Schema` => `X-Meeshkan-Scheme`.
- Use dash instead of underscores in parameters (`--admin_port` => `--admin-port` and similar).
- Fix help text for the `-r, --header_routing` parameter to the mock command to say header routing, not path routing.
- Update `tools.meeshkan_server.server.callbacks.callback` => `meeshkan_server.server.callbacks.callback`.
Note that SERVER.md has not been updated, as it has been deleted in https://github.com/meeshkan/meeshkan/pull/82.
=> Improve documentation and argument handling

README.md
We should soon move to inferring source type from the scheme. #76
=> Remove docs on --source

meeshkan/server/server/views.py, tests/server/server/callbacks/callbacks.py, tests/server/server/test_body_echoing.py
Calling`str(self.request.body)` when self.request.body is a bytes instance does not work, instead we should decode the bytes.
Since we now get the correct decoded body, we can drop `_extract_json_safel` as py-http-types takes care of the same thing.
=> Fix body decoding in MockServerView

docs/MOCK.md, meeshkan/server/commands.py, meeshkan/server/server/callbacks.py, meeshkan/server/server/server.py
Callback usage should be explicit and not default to some directory.
Avoid this default directory gets rid of this startup message for everyone not using callbacks:
> DEBUG - Callback configuration path doesn't exist ./callbacks
Instead we can now exit with an error if the specified callbacks directory does not exist, instead of just noting it at DEBUG level.
Also rename --callback-path to --callback-dir to harmonize with --specs-dir and --log-dir naming.
=> Do not use a default callbacks directory

.circleci/config.yml, .flake8, README.md, setup.py
Now that there are multiple contributors to `meeshkan`, I think we could add formatting and style checks. This PR adds `black` and `flake8` following the example of https://github.com/meeshkan/py-http-types/pull/21 . Style checks are not yet fixed as there are so many of them and they probably require manual work. Therefore the linting step is also skipped in `python setup.py test`. 
- ~**You should only review `setup.py` and `README.md`, everything else is auto-formatted with black**~
- Suggestion for contributors: Switch on auto-formatting with black in your code editor
=> Add formatting and style-checks.

meeshkan/serve/commands.py, meeshkan/serve/mock/callbacks.py
Let click validate that the callback directory exists. Fixes #105.
Replaced #108 with this, thanks @aby2s for the tip about letting click validate the parameters.
=> Replace sys.exit() with exception

meeshkan/logging.yaml, meeshkan/serve/admin/runner.py, meeshkan/serve/mock/server.py
- What do you think about this change?
- Should we use a different log format for when running as a daemon?
Before
```sh
$ meeshkan record
2020-03-11 15:16:25,205 - meeshkan.serve.admin.runner - INFO - Starting admin endpont on http://localhost:8888/admin
2020-03-11 15:16:25,205 - meeshkan.serve.record.proxy - INFO - Starting Meeshkan record on http://localhost:8000
2020-03-11 15:16:25,205 - meeshkan.serve.record.proxy - INFO - Spec generation mode is disabled
```
After:
```sh
$ meeshkan record
Starting admin endpoint on http://localhost:8888/admin
Starting Meeshkan record on http://localhost:8000
Spec generation mode is disabled
```
Future improvements could be adding color and/or emojis to make the output come alive a bit.
=> Shorten log format

README.md, docs/BUILD.md, docs/MOCK.md, docs/RECORD.md
We show installations instructions once, we don't need to nag about `pip install meeshkan` later on, especially as people now may start installing the tool using other ways such as homebrew or apt.
=> Avoid nagging about 'pip install meeshkan'

meeshkan/serve/mock/response_matcher.py
Fixes a bug, the intention is most likely to check if the matched method is none instead of checking if request has no method.
=> Check if matched method is none instead of checking request method.

meeshkan/serve/admin/runner.py, meeshkan/serve/admin/views.py, meeshkan/serve/mock/server.py, meeshkan/serve/mock/views.py, tests/serve/mock/test_views.py
When creating `MockServerView`, its dependencies are injected either via a global variable (`callback_manager` loaded from given directory) or via `MeeshkanApplication`. I think the "official" way to inject dependencies is to use [RequestHandler.initialize](https://www.tornadoweb.org/en/stable/web.html#entry-points), to me it makes the flow easier to understand as it's more explicit.
~I would also like to avoid using a global `callback_manager` as it makes the tests dependent on each other, couldn't one just create a new `CallbackManager` when creating a server?~ Now I understand why it's a global, it's because the decorators need to add callbacks somewhere.
What do you think?
=> Avoid globals when initializing views.

meeshkan/__main__.py
The initial `--help` output should be as brief as possible and show information about using the tool itself.
In #121 we discussed improving our elevator pitch (one sentence summary). But after feedback from Nikolay and looking around at other tools, I don't think that belongs in the `--help` output, so we can probably just remove the `Meeshkan CLI` sentence completely.
Before this PR:
```sh
$ meeshkan --help
Usage: meeshkan [OPTIONS] COMMAND [ARGS]...
Meeshkan CLI.
Options:
--version  Show the version and exit.
--help     Show this message and exit.
Commands:
build    Build an OpenAPI specification from HTTP recordings.
convert  Convert recordings from PCAP to JSONL format.
mock     Run a mock server using OpenAPI specifications.
record   Record HTTP traffic from a reverse proxy.
``` …
=> Remove the "Meeshkan CLI" sentence from --help

.isort.cfg, meeshkan/serve/admin/runner.py, meeshkan/serve/commands.py, meeshkan/serve/mock/matcher.py, meeshkan/serve/mock/response_matcher.py, meeshkan/serve/mock/rest.py, meeshkan/serve/mock/server.py, meeshkan/serve/mock/specs.py, setup.py, tests/serve/mock/end-to-end/opbank/test_opbank.py, tests/serve/mock/test_body_echoing.py, tests/serve/mock/test_control_via_rest.py, tests/serve/mock/test_matcher.py, tests/serve/mock/test_mocking_server_gen_petstore.py, tests/serve/mock/test_mocking_server_gen_stripe.py, tests/serve/record/test_proxy.py
Also introduce a `OpenAPISpecification` dataclass containing the API object and source information, instead of sending around a dict mapping from source to API object, and extract the loading of specs out from ResponseMatcher.
Current log output at startup:
```sh
$ meeshkan mock --specs-dir tests/serve/mock/schemas/petstore 
Starting admin endpoint on http://localhost:8888/admin
Mock is listening on http://localhost:8000
```
After this PR:
```sh
$ meeshkan mock --specs-dir tests/serve/mock/schemas/petstore 
⚙ Admin   http://localhost:8888/admin
→ GET     http://localhost:8000/http://petstore.swagger.io/pets
→ POST    http://localhost:8000/http://petstore.swagger.io/pets
→ GET     http://localhost:8000/http://petstore.swagger.io/pets/{petId}
```
In the future I think we should show an …
=> Log endpoints at startup

meeshkan/serve/admin/runner.py
Replace ⚙, which looks ugly depending on the font, with the more discrete •
=> Avoid ugly emoji for admin endpoint

meeshkan/serve/admin/runner.py, meeshkan/serve/admin/views.py, meeshkan/serve/mock/scope.py, meeshkan/serve/mock/server.py, meeshkan/serve/record/proxy.py, tests/serve/admin/test_rest_middleware.py, tests/serve/admin/test_scope.py, tests/test_main.py
Scope is a way to signal the current scope of the test.
For example, if we are testing A and then B, we set
the scope to A and then B, and by querying the scope, we can
assign API requests and responses to their logical "place"
in things like reports.
=> Adds scope for server

tests/serve/mock/test_mocking_server_gen_fails.py, tests/serve/mock/test_mocking_server_gen_petstore.py
Fixes pytest warning:
```
PytestCollectionWarning: cannot collect test class 'TestSink' because it has a __init__ constructor (from: tests/serve/mock/test_mocking_server_gen_fails.py)
class TestSink(AbstractSink):
```
=> Rename TestSink to MockSink to avoid pytest warnings.

docs/MOCK.md, meeshkan/serve/commands.py, meeshkan/serve/mock/specs.py, tests/serve/mock/test_control_via_rest.py, tests/serve/mock/test_specs.py
Remove the `-s,--specs-dir` option, so instead of
meeshkan mock --specs-dir path/to/dir/
one runs
meeshkan mock path/to/dir/
Also enhance it, so it can accept files as well:
meeshkan mock path/to/spec.yaml
and http(s) urls:
meeshkan mock https://example.com/spec.yaml
and multiple arguments:
meeshkan mock spec1 spec2 [...]
meeshkan mock examples/*stripe*
To do this it removes the (start, stop, status) subcommands to the mock command, which also simplifies help output, and replaces stopping and status of daemon with flags to meeshkan mock.
=> Simplify and enhance mock specs handling

README.md, docs/BUILD.md, docs/MOCK.md, docs/RECORD.md
References #106.
I know there are discussions around restructuring the documentation and how we present Meeshkan as a developer tool. But in the meantime, I thought it'd be useful to update our existing documentation based on the points of improvement @fornwall and I outlined last week.
This PR covers the following (ended up bigger than I had initially planned 🙈):
- Update docs to reflect recordings filename changes in #100 
- Update docs to default build output changes in #99 
- Better flag descriptions in BUILD.md (ie the differences between using `-o` and `-a`)
- Link to instructions for installing curl or any other tool we mention
- Explain what a daemon is (provided link)
- Links to the next section at the end of each docs page
- Always write out the long format of options (like …
=> Docs: Polish initial impression of running Meeshkan

meeshkan/logging.yaml
This changes the terminal output for a single http access from:
```
Request(method=<HttpMethod.GET: 'get'>, headers={'Host': 'petstore.swagger.i
o', 'User-Agent': 'curl/7.64.1', 'Accept': '*/*'}, query={}, host='petstore.
swagger.io', path='/v1/pets', pathname='/v1/pets', protocol=<Protocol.HTTP:
'http'>, bodyAsJson='', timestamp=None, body='')
400 GET /http://petstore.swagger.io/v1/pets (::1) 7.80ms
```
to only keep the second line:
```
400 GET /http://petstore.swagger.io/v1/pets (::1) 7.80ms
```
=> Change console logging level from DEBUG to INFO

setup.py
There is a python 3.8+ compatibility issue with daemonocle:
https://github.com/jnrbsn/daemonocle/pull/24
Until that fix is applied upstream (or us switching to another daemon library) we're switching to [our fork of the daemonocle library](https://github.com/meeshkan/daemonocle) with the above linked fix applied.
=> Fix daemon mode under python 3.8+ (fixes #165)

meeshkan/build/builder.py, meeshkan/build/json_schema.py, meeshkan/build/media_types.py, meeshkan/build/operation.py, meeshkan/build/param.py, meeshkan/build/paths.py, meeshkan/build/result.py, meeshkan/build/schemadiff.py, meeshkan/build/servers.py, meeshkan/build/update_mode.py, meeshkan/build/writer.py, pyproject.toml, tests/build/test_builder.py, tests/build/test_json_schema.py, tests/build/test_paths.py, tests/build/test_query.py, tests/build/test_servers.py
Fixes a configuration bug where `meeshkan/build` folder was neglected by Black as it excludes "build" pattern by default. Only new addition here is the `pyproject.toml` and running `black .`.
Required for #179
=> Fix black configuration.

setup.py
Doing this makes us compatible with the
python3 -m venv .venv
setup, without any extra step required to use virtualenv or upgrade setuptools.
=> Replace setuptools.errors with distutils.errors

pytest.ini, tests/build/test_builder.py
- All tests in `tests/build` were previously not discovered by pytest as it does not recurse into a folder named `build` by default.
In another PR:
=> Add tests/build as test path.

README.md
Since python 3.3 venv comes preinstalled with python, and is the recommended tool to use: https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#installing-virtualenv
> Installing virtualenv
> Note: If you are using Python 3.3 or newer, the venv module is the preferred way to create and manage virtual environments. venv is included in the Python standard library and requires no additional installation. If you are using venv, you may skip this section.
=> Replace virtualenv with venv in the README

.circleci/config.yml, .isort.cfg, pyproject.toml, tests/conftest.py, tests/serve/admin/test_storage.py, tests/serve/mock/faker/test_stateful_faker.py, tests/serve/mock/faker/test_stateless_faker.py, tests/serve/mock/storage/test_entity.py, tests/serve/mock/storage/test_mock_data.py, tests/serve/mock/storage/test_mock_data_store.py
- Removes `pipenv` from CircleCI build
- Reverts to explicitly using `pytest` and `black .` in CircleCI: invoking those from `python setup.py test` has the side-effect that for some reason the configuration `pyproject.toml` isn't read so Black tries to format `venv` folder
=> Remove pipenv from circleci.

.circleci/config.yml, .isort.cfg, meeshkan/build/builder.py, meeshkan/build/media_types.py, setup.py, tests/build/test_builder.py
- Doesn't handle workspace persistence or any kind of workflow optimization
- Uses `pre-commit run --all-files` when `python setup.py format` is run
- Fixes broken formatting in `meeshkan/build` and `tests/build`
=> Check formatting in separate CI job

hmt/build/builder.py, hmt/serve/mock/server.py, hmt/serve/record/proxy.py, hmt/tutorial/__init__.py
I'm working on an HMT tutorial and realized that the logs still say `Meeshkan is running` or `Starting Meeshkan on...` so this PR updates that to HMT 💫 
I also created a branch (`rename-logs-from-main`) that makes these changes to `main` in case you decide to make that the default.
If anyone has advice for fixing the [failing CircleCI builds](https://app.circleci.com/pipelines/github/meeshkan/hmt), that'd be great. I know I need to update the node version in order to install and run pyright but I'm not exactly sure where... 🤔
=> Rename Meeshkan to HMT in logs
